Traceback (most recent call last):
  File "zlel_main.py", line 26, in <module>
    zl1.solveCircuit(filename)
  File "C:\Users\Pello Usabiaga\Documents\GitHub repositorios\IE\ZLEL\ZLEL-proiektua\zlel\zlel_p1_errore_kontrola.py", line 978, in solveCircuit
    [cir_el, cir_nd, cir_val, cir_ctr, orders] = cir_parser(filename)
  File "C:\Users\Pello Usabiaga\Documents\GitHub repositorios\IE\ZLEL\ZLEL-proiektua\zlel\zlel_p1_errore_kontrola.py", line 170, in cir_parser
    raise ValueError
ValueError
