Traceback (most recent call last):
  File "zlel_main.py", line 26, in <module>
    zl1.solveCircuit(filename)
  File "D:\Documentos\Github\ZLEL proiektua\zlel\zlel_p1_errore_kontrola.py", line 944, in solveCircuit
    [cir_el, cir_nd, cir_val, cir_ctr, orders] = cir_parser(filename)
  File "D:\Documentos\Github\ZLEL proiektua\zlel\zlel_p1_errore_kontrola.py", line 163, in cir_parser
    raise ValueError
ValueError
