Traceback (most recent call last):
  File "zlel_main.py", line 26, in <module>
    zl1.solveCircuit(filename)
  File "D:\Documentos\Github\ZLEL proiektua\zlel\zlel_p1_errore_kontrola.py", line 902, in solveCircuit
    [cir_el, cir_nd, cir_val, cir_ctr, orders] = cir_parser(filename)
  File "D:\Documentos\Github\ZLEL proiektua\zlel\zlel_p1_errore_kontrola.py", line 118, in cir_parser
    file = np.array(np.loadtxt(filename, dtype=str))
  File "D:\Programas\Programacion\Anaconda\lib\site-packages\numpy\lib\npyio.py", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "D:\Programas\Programacion\Anaconda\lib\site-packages\numpy\lib\_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "D:\Programas\Programacion\Anaconda\lib\site-packages\numpy\lib\_datasource.py", line 532, in open
    return _file_openers[ext](found, mode=mode,
PermissionError: [Errno 13] Permission denied: 'cirs/\\opamp'
